package principal;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thalys fabrete
 */

public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }
    public static String tipoVacinaSelecionada = "COVID - 1ª dose"; // valor default
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupTipoVacina = new javax.swing.ButtonGroup();
        menuPopUpTabela = new javax.swing.JPopupMenu();
        opInserir = new javax.swing.JMenuItem();
        opExcluir = new javax.swing.JMenuItem();
        PainelDadosPessoais = new javax.swing.JPanel();
        lblCpf = new javax.swing.JLabel();
        lblNome1 = new javax.swing.JLabel();
        iptTxtNome1 = new javax.swing.JTextField();
        iptTxtCpf = new javax.swing.JTextField();
        painelTipoVacina = new javax.swing.JPanel();
        btnRadioCovid01 = new javax.swing.JRadioButton();
        btnRadioCovid02 = new javax.swing.JRadioButton();
        btnRadioOutras = new javax.swing.JRadioButton();
        lblNomeVacina = new javax.swing.JLabel();
        selectNomeVacina = new javax.swing.JComboBox<>();
        painel1Dose = new javax.swing.JPanel();
        lblData1Dose = new javax.swing.JLabel();
        iptTxtData1Dose = new javax.swing.JTextField();
        painel2Dose = new javax.swing.JPanel();
        lblData2Dose2 = new javax.swing.JLabel();
        iptTxtData2Dose = new javax.swing.JTextField();
        btnLimpar = new javax.swing.JButton();
        btnInserir1 = new javax.swing.JButton();
        painelResumo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAgendamentos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblSublinhado_AgendaVacinacao = new javax.swing.JLabel();

        opInserir.setText("Inserir");
        opInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserir1ActionPerformed(evt);
            }
        });
        menuPopUpTabela.add(opInserir);

        opExcluir.setText("Excluir");
        opExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opExcluirActionPerformed(evt);
            }
        });
        menuPopUpTabela.add(opExcluir);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PainelDadosPessoais.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 51)), "Dados Pessoais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N

        lblCpf.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblCpf.setText("CPF:");

        lblNome1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblNome1.setText("Nome:");

        iptTxtNome1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        iptTxtNome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iptTxtNome1ActionPerformed(evt);
            }
        });

        iptTxtCpf.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        iptTxtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iptTxtCpfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelDadosPessoaisLayout = new javax.swing.GroupLayout(PainelDadosPessoais);
        PainelDadosPessoais.setLayout(PainelDadosPessoaisLayout);
        PainelDadosPessoaisLayout.setHorizontalGroup(
            PainelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelDadosPessoaisLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblCpf)
                .addGap(18, 18, 18)
                .addComponent(iptTxtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(PainelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PainelDadosPessoaisLayout.createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addComponent(lblNome1)
                    .addContainerGap(422, Short.MAX_VALUE)))
            .addGroup(PainelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PainelDadosPessoaisLayout.createSequentialGroup()
                    .addGap(100, 100, 100)
                    .addComponent(iptTxtNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        PainelDadosPessoaisLayout.setVerticalGroup(
            PainelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelDadosPessoaisLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(PainelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iptTxtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCpf))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PainelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PainelDadosPessoaisLayout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(lblNome1)
                    .addContainerGap(57, Short.MAX_VALUE)))
            .addGroup(PainelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PainelDadosPessoaisLayout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(iptTxtNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(51, Short.MAX_VALUE)))
        );

        getContentPane().add(PainelDadosPessoais, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 520, -1));

        painelTipoVacina.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 51)), "Dados Pessoais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N

        btnGroupTipoVacina.add(btnRadioCovid01);
        btnRadioCovid01.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnRadioCovid01.setSelected(true);
        btnRadioCovid01.setText("COVID - 1ª dose");
        btnRadioCovid01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadioCovid01ActionPerformed(evt);
            }
        });

        btnGroupTipoVacina.add(btnRadioCovid02);
        btnRadioCovid02.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnRadioCovid02.setText("COVID - 2ª dose");
        btnRadioCovid02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadioCovid02ActionPerformed(evt);
            }
        });

        btnGroupTipoVacina.add(btnRadioOutras);
        btnRadioOutras.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnRadioOutras.setText("Outras");
        btnRadioOutras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadioOutrasActionPerformed(evt);
            }
        });

        lblNomeVacina.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblNomeVacina.setText("Nome da vacina:");

        selectNomeVacina.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        selectNomeVacina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CoronaVac", "AstraZeneca      ", "Pfizer" }));
        selectNomeVacina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectNomeVacinaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelTipoVacinaLayout = new javax.swing.GroupLayout(painelTipoVacina);
        painelTipoVacina.setLayout(painelTipoVacinaLayout);
        painelTipoVacinaLayout.setHorizontalGroup(
            painelTipoVacinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTipoVacinaLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(painelTipoVacinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelTipoVacinaLayout.createSequentialGroup()
                        .addComponent(lblNomeVacina)
                        .addGap(18, 18, 18)
                        .addComponent(selectNomeVacina, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelTipoVacinaLayout.createSequentialGroup()
                        .addComponent(btnRadioCovid01)
                        .addGap(18, 18, 18)
                        .addComponent(btnRadioCovid02)
                        .addGap(18, 18, 18)
                        .addComponent(btnRadioOutras)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        painelTipoVacinaLayout.setVerticalGroup(
            painelTipoVacinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTipoVacinaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(painelTipoVacinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRadioCovid02)
                    .addComponent(btnRadioCovid01)
                    .addComponent(btnRadioOutras))
                .addGap(18, 18, 18)
                .addGroup(painelTipoVacinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeVacina)
                    .addComponent(selectNomeVacina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(painelTipoVacina, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        painel1Dose.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 51)), "1ª Dose", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N

        lblData1Dose.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblData1Dose.setText("Data:");

        iptTxtData1Dose.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        iptTxtData1Dose.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                iptTxtData1DoseFocusLost(evt);
            }
        });

        javax.swing.GroupLayout painel1DoseLayout = new javax.swing.GroupLayout(painel1Dose);
        painel1Dose.setLayout(painel1DoseLayout);
        painel1DoseLayout.setHorizontalGroup(
            painel1DoseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel1DoseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblData1Dose)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(iptTxtData1Dose, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painel1DoseLayout.setVerticalGroup(
            painel1DoseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel1DoseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel1DoseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblData1Dose)
                    .addComponent(iptTxtData1Dose, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(painel1Dose, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, 100));

        painel2Dose.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 51)), "2ª Dose", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N

        lblData2Dose2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblData2Dose2.setText("Data:");

        iptTxtData2Dose.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        iptTxtData2Dose.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                iptTxtData2DoseFocusLost(evt);
            }
        });
        iptTxtData2Dose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iptTxtData2DoseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painel2DoseLayout = new javax.swing.GroupLayout(painel2Dose);
        painel2Dose.setLayout(painel2DoseLayout);
        painel2DoseLayout.setHorizontalGroup(
            painel2DoseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel2DoseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblData2Dose2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(iptTxtData2Dose, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painel2DoseLayout.setVerticalGroup(
            painel2DoseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel2DoseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel2DoseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblData2Dose2)
                    .addComponent(iptTxtData2Dose, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(painel2Dose, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 260, 100));

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, 126, 40));

        btnInserir1.setText("Inserir");
        btnInserir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserir1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnInserir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 126, 40));

        painelResumo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 51)), "Resumo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N

        tableAgendamentos.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        tableAgendamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF", "Tipo Vacina", "Nome Vacina", "Data 1", "Data 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableAgendamentos.setComponentPopupMenu(menuPopUpTabela);
        jScrollPane1.setViewportView(tableAgendamentos);

        javax.swing.GroupLayout painelResumoLayout = new javax.swing.GroupLayout(painelResumo);
        painelResumo.setLayout(painelResumoLayout);
        painelResumoLayout.setHorizontalGroup(
            painelResumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelResumoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelResumoLayout.setVerticalGroup(
            painelResumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelResumoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162))
        );

        getContentPane().add(painelResumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 530, 311));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Agenda de Vacinação");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 13, -1, -1));

        lblSublinhado_AgendaVacinacao.setFont(new java.awt.Font("Tahoma", 1, 5)); // NOI18N
        lblSublinhado_AgendaVacinacao.setForeground(new java.awt.Color(51, 51, 255));
        lblSublinhado_AgendaVacinacao.setText("_______________________________________________________________________________");
        getContentPane().add(lblSublinhado_AgendaVacinacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 37, 262, 8));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRadioOutrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadioOutrasActionPerformed
        selectNomeVacina.removeAllItems();
        Vacinas.outras.forEach(vacina -> selectNomeVacina.addItem(vacina));
        painel1Dose.setVisible(true);
        painel2Dose.setVisible(false);
        iptTxtData1Dose.setText("");
        iptTxtData2Dose.setText("");
        tipoVacinaSelecionada = btnRadioOutras.getText();
        
        
    }//GEN-LAST:event_btnRadioOutrasActionPerformed

    private void iptTxtNome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iptTxtNome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iptTxtNome1ActionPerformed

    private void iptTxtData2DoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iptTxtData2DoseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iptTxtData2DoseActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // Limpando todos campos
        iptTxtNome1.setText("");
        iptTxtCpf.setText("");    
        iptTxtData1Dose.setText("");
        iptTxtData2Dose.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnInserir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserir1ActionPerformed
        // Recuperando dados ...
        String nome = iptTxtNome1.getText();
        String CPF = iptTxtCpf.getText();
        String tipoVacina = tipoVacinaSelecionada;
        String nomeVacina = selectNomeVacina.getSelectedItem().toString();
        String data1Dose = "";
        String data2Dose = "";
        if(tipoVacina.toUpperCase().equals("Outras".toUpperCase()) || tipoVacina.toUpperCase().equals("COVID - 1ª dose".toUpperCase()))
        {
            data1Dose = iptTxtData1Dose.getText();
        }
        if(tipoVacina.toUpperCase().equals("COVID - 2ª dose".toUpperCase()) || tipoVacina.toUpperCase().equals("COVID - 1ª dose".toUpperCase()))
        {
            data2Dose = iptTxtData2Dose.getText();
        }
        
        Agendamento novoAgendamento = new Agendamento(nome, CPF, tipoVacina, nomeVacina, data1Dose, data2Dose);
        if(validarCampos())
        {
            insereNaTabela(novoAgendamento);
        }        
    }//GEN-LAST:event_btnInserir1ActionPerformed
    private void insereNaTabela(Agendamento novoAgendamento)  
    {
        ((DefaultTableModel) tableAgendamentos.getModel()).addRow(new Object[4]);
        int linhaAtual = tableAgendamentos.getRowCount() - 1;
        int i = 0;
        
        tableAgendamentos.setValueAt(novoAgendamento.getNome(), linhaAtual, i++);
        tableAgendamentos.setValueAt(novoAgendamento.getCPF(), linhaAtual, i++);
        tableAgendamentos.setValueAt(novoAgendamento.getTipoVacina(), linhaAtual, i++);
        tableAgendamentos.setValueAt(novoAgendamento.getNomeVacina(), linhaAtual, i++);
        tableAgendamentos.setValueAt(novoAgendamento.getData1Dose(), linhaAtual, i++);
        tableAgendamentos.setValueAt(novoAgendamento.getData2Dose(), linhaAtual, i++);
    }
    private void iptTxtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iptTxtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iptTxtCpfActionPerformed

    private void btnRadioCovid01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadioCovid01ActionPerformed
        preencherSelectCovid();
        painel1Dose.setVisible(true);
        painel2Dose.setVisible(true);
        
        tipoVacinaSelecionada = btnRadioCovid01.getText();
    }//GEN-LAST:event_btnRadioCovid01ActionPerformed

    private void btnRadioCovid02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadioCovid02ActionPerformed
        preencherSelectCovid();
        painel1Dose.setVisible(false);
        painel2Dose.setVisible(true);
        iptTxtData1Dose.setText("");
        iptTxtData2Dose.setText("");
        
        tipoVacinaSelecionada = btnRadioCovid02.getText();
    }//GEN-LAST:event_btnRadioCovid02ActionPerformed
    public void preencherSelectCovid()
    {
        selectNomeVacina.removeAllItems();
        Vacinas.covid.forEach(vacina -> selectNomeVacina.addItem(vacina));
    }
    private void iptTxtData1DoseFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_iptTxtData1DoseFocusLost
        alterarDataSegundaDose();
    }//GEN-LAST:event_iptTxtData1DoseFocusLost

    private void selectNomeVacinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectNomeVacinaActionPerformed
        if(selectNomeVacina.hasFocus())  
        {
            alterarDataSegundaDose();
        }
    }//GEN-LAST:event_selectNomeVacinaActionPerformed

    private void iptTxtData2DoseFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_iptTxtData2DoseFocusLost
        if(selectNomeVacina.getSelectedIndex() != -1)
        {
            inserirManualmenteSegundaDose();
        }
    }//GEN-LAST:event_iptTxtData2DoseFocusLost

    private void opExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opExcluirActionPerformed
        int linhaSelecionada = tableAgendamentos.getSelectedRow();
        
        if(linhaSelecionada != -1)
        {
            ((DefaultTableModel) tableAgendamentos.getModel()).removeRow(linhaSelecionada);
        }
    }//GEN-LAST:event_opExcluirActionPerformed
    private boolean inserirManualmenteSegundaDose()
    {
        Date data1 = new Date();
        Date data2 = new Date();
        Calendar cal1 = Calendar.getInstance();
        Calendar cal2 = Calendar.getInstance();
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        String msgErro = "";
        String msgTitle = "";
        try
        {
            data1 = format.parse(iptTxtData1Dose.getText());
            data2 = format.parse(iptTxtData2Dose.getText());
            cal1.setTime(data1);
            cal2.setTime(data2);
            String vacinaSelecionada = selectNomeVacina.getSelectedItem().toString().toUpperCase();
            cal2.add(Calendar.DATE, - cal1.get(Calendar.DAY_OF_YEAR));
            
            if(vacinaSelecionada.equals("CoronaVac".toUpperCase()))
            {
                if(!(cal2.get(Calendar.DAY_OF_YEAR) >= 14 && cal2.get(Calendar.DAY_OF_YEAR) <= 28))
                {
                    msgErro = "A data da segunda dose deve estar entre 14 e 28 dias após\n" +
                               "a data da primeira dose";
                    msgTitle = "Data inválida para 2ª dose da vacina CoronaVac!";
                }
            }
            else if(vacinaSelecionada.equals("Pfizer".toUpperCase()))
            {
                if(!(cal2.get(Calendar.DAY_OF_YEAR) >= 21 && cal2.get(Calendar.DAY_OF_YEAR) <= 30))
                {
                    msgErro = "A data da segunda dose deve estar entre 21 e 30 dias após a\n" +
                                "data da primeira dose";
                    msgTitle = "Data inválida para 2ª dose da vacina Pfizer!";
                }
            }
            else
            {
                if(!(cal2.get(Calendar.DAY_OF_YEAR) >= 77 && cal2.get(Calendar.DAY_OF_YEAR) <= 84))
                {
                    msgErro = "A data da segunda dose deve estar entre 77 e 84 dias\n" +
                               "após a data da primeira dose";
                    msgTitle = "Data inválida para 2ª dose da vacina AstraZeneca!";
                }
            }
        }
        catch(ParseException ex)
        {
            //System.out.println("Data não foi preenchida corretamente! \n MSG: " + ex.getMessage());
        }
        if(!msgErro.isEmpty())
        {
            JOptionPane.showMessageDialog(this, msgErro, msgTitle, JOptionPane.ERROR_MESSAGE); 
            return false;
        }
        return true;
    }
    private boolean validarCampos()
    {
        // Validandos Campos segundo algumas regras:
        // O campo nome não pode estar vazio 
        // O campo CPF não pode estar vazio
        // A primeira dose (se houver) e a segunda dose(se houver) não podem estar vazias e devem ser datas válidas
        String errorMsg = "";
        String titleMsg = "Erro de validação de campos!";
        if(iptTxtNome1.getText().isEmpty())
        {
            errorMsg += "Campo nome não pode estar vazio\n";
        }
        if(iptTxtCpf.getText().isEmpty())
        {
            errorMsg += "Campo CPF não pode estar vazio\n";
        }
        if(!Validacoes.isCPF(iptTxtCpf.getText()))
        {
            errorMsg += "o CPF deve ser válido\n";
        }
        if(
            (iptTxtData1Dose.getText().isEmpty() && btnRadioCovid01.isSelected())
            || 
            (iptTxtData1Dose.getText().isEmpty() && btnRadioOutras.isSelected())    
            )
        {
            errorMsg += "Data da primeira dose não pode estar vazia\n";
        } 
        if((iptTxtData2Dose.getText().isEmpty()) && !btnRadioOutras.isSelected())
        {
            errorMsg += "Data da segunda dose não pode estar vazia\n";
        } 
        if(
            (!Validacoes.isDateValid(iptTxtData1Dose.getText()) && btnRadioCovid01.isSelected())
            || 
            (!Validacoes.isDateValid(iptTxtData1Dose.getText()) && btnRadioOutras.isSelected())    
            )
        {
            errorMsg += "Data da primeira dose deve ser uma data válida\n";
        } 
        if(!Validacoes.isDateValid(iptTxtData2Dose.getText()) && !btnRadioOutras.isSelected())
        {
            errorMsg += "Data da segunda dose deve ser uma data válida\n";
        } 
       if(!inserirManualmenteSegundaDose()){
            return false;
       }     
       else if(!errorMsg.isEmpty())
       {
           JOptionPane.showMessageDialog(this, errorMsg, titleMsg, JOptionPane.WARNING_MESSAGE); 
           return false;
       }
       return true;
    }
    private void alterarDataSegundaDose()
    {
        Date data1 = new Date();
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        Boolean dateOk = false;
        try
        {
            data1 = format.parse(iptTxtData1Dose.getText());
            cal.setTime(data1);
            String vacinaSelecionada = selectNomeVacina.getSelectedItem().toString().toUpperCase();
            if(vacinaSelecionada.equals("CoronaVac".toUpperCase()) || vacinaSelecionada.equals("Pfizer".toUpperCase()))
            {
                cal.add(Calendar.DAY_OF_YEAR, 21);
                dateOk = true;
            }
            else
            {
                cal.add(Calendar.DAY_OF_YEAR, 80);
                dateOk = true;
            }
            if(dateOk)
            {
                data1 = cal.getTime();
                iptTxtData2Dose.setText(format.format(data1));
            }
            
        }
        catch(ParseException ex)
        {
            //System.out.println("Data não foi preenchida corretamente! \n MSG: " + ex.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelDadosPessoais;
    private javax.swing.ButtonGroup btnGroupTipoVacina;
    private javax.swing.JButton btnInserir1;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JRadioButton btnRadioCovid01;
    private javax.swing.JRadioButton btnRadioCovid02;
    private javax.swing.JRadioButton btnRadioOutras;
    private javax.swing.JTextField iptTxtCpf;
    private javax.swing.JTextField iptTxtData1Dose;
    private javax.swing.JTextField iptTxtData2Dose;
    private javax.swing.JTextField iptTxtNome1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblData1Dose;
    private javax.swing.JLabel lblData2Dose2;
    private javax.swing.JLabel lblNome1;
    private javax.swing.JLabel lblNomeVacina;
    private javax.swing.JLabel lblSublinhado_AgendaVacinacao;
    private javax.swing.JPopupMenu menuPopUpTabela;
    private javax.swing.JMenuItem opExcluir;
    private javax.swing.JMenuItem opInserir;
    private javax.swing.JPanel painel1Dose;
    private javax.swing.JPanel painel2Dose;
    private javax.swing.JPanel painelResumo;
    private javax.swing.JPanel painelTipoVacina;
    private javax.swing.JComboBox<String> selectNomeVacina;
    private javax.swing.JTable tableAgendamentos;
    // End of variables declaration//GEN-END:variables
}