/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogodaforca_clienteudp;

import javax.swing.JOptionPane;

/**
 *
 * @author thaly
 */
public class ClienteForm extends javax.swing.JFrame {

    private JogoDaForca_ClienteUDP meuCliente;

    public ClienteForm() {
        this.meuCliente = new JogoDaForca_ClienteUDP("DNS");
        meuCliente.setJogador(JOptionPane.showInputDialog(this, "Nome do jogador"));
        initComponents();
        solicitarNovaPalavra();
        exibirPontuacao();
        txtJogador.setText(meuCliente.getJogador());
    }

    private void solicitarNovaPalavra() {
        if (meuCliente.getJogador() != null) {
            meuCliente.solicitarMascara();
            txtPalavra.setText(meuCliente.getMascara());
        }
    }

    private void exibirPontuacao() {
        if (meuCliente.getJogador() != null) {
            txtChances.setText(String.valueOf(meuCliente.getChances()));
        }
    }

    private void exibirLetrasTentadas() {
        if (meuCliente.getJogador() != null) {
            txtLetrasTentadas.setText(meuCliente.getLetrasTentadas());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNovoTermo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtPalavra = new javax.swing.JTextField();
        letraChute = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnEnviarLetra = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtChances = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtJogador = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtLetrasTentadas = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtResultado = new javax.swing.JTextField();
        btnPlacar = new javax.swing.JButton();
        btnMeuHistorico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnNovoTermo.setText("Novo Termo");
        btnNovoTermo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoTermoActionPerformed(evt);
            }
        });

        jLabel2.setText("Palavra:");

        txtPalavra.setEditable(false);
        txtPalavra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPalavraActionPerformed(evt);
            }
        });

        letraChute.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                letraChuteKeyReleased(evt);
            }
        });

        jLabel3.setText("Digite a letra que você acha que contém na palavra acima, depois clique em enviar:");

        btnEnviarLetra.setText("Enviar");
        btnEnviarLetra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarLetraActionPerformed(evt);
            }
        });

        jLabel4.setText("Chances:");

        txtChances.setEditable(false);
        txtChances.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtChances.setForeground(new java.awt.Color(51, 255, 0));
        txtChances.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChancesActionPerformed(evt);
            }
        });

        jLabel5.setText("Jogador:");

        txtJogador.setEditable(false);
        txtJogador.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtJogador.setForeground(new java.awt.Color(51, 255, 0));
        txtJogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJogadorActionPerformed(evt);
            }
        });

        jLabel1.setText("Letras já tentadas:");

        txtLetrasTentadas.setEditable(false);
        txtLetrasTentadas.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtLetrasTentadas.setForeground(new java.awt.Color(0, 51, 255));
        txtLetrasTentadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLetrasTentadasActionPerformed(evt);
            }
        });

        jLabel6.setText("Resultado:");

        txtResultado.setEditable(false);
        txtResultado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtResultado.setForeground(new java.awt.Color(51, 255, 0));
        txtResultado.setText("Indefinido");
        txtResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultadoActionPerformed(evt);
            }
        });

        btnPlacar.setText("Placar");
        btnPlacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlacarActionPerformed(evt);
            }
        });

        btnMeuHistorico.setText("Meu Histórico");
        btnMeuHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMeuHistoricoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(209, 209, 209))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtChances, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(73, 73, 73)
                                                .addComponent(jLabel5)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(34, 34, 34))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(letraChute, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(206, 206, 206))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnEnviarLetra)
                                        .addGap(197, 197, 197))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPalavra, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnNovoTermo)
                            .addComponent(jLabel1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLetrasTentadas))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(btnPlacar)
                                .addGap(51, 51, 51)
                                .addComponent(btnMeuHistorico)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtChances, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPalavra, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(letraChute, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEnviarLetra)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addComponent(txtLetrasTentadas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovoTermo)
                    .addComponent(btnPlacar)
                    .addComponent(btnMeuHistorico))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoTermoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoTermoActionPerformed
        if (meuCliente.getChances() == 0 || !meuCliente.getMascara().contains("_")) {
            solicitarNovaPalavra();
            exibirPontuacao();
            exibirLetrasTentadas();
        } else {
            JOptionPane.showMessageDialog(this, "Antes de iniciar um novo jogo, finalize o que está em andamento!");
        }
    }//GEN-LAST:event_btnNovoTermoActionPerformed

    private void txtPalavraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPalavraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPalavraActionPerformed

    private void btnEnviarLetraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarLetraActionPerformed
        if (meuCliente.getJogador() != null) {
            String letra = letraChute.getText();
            if (letra.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Infelizmente meu amigo, você não sabe jogar, vai ter que aprender. Insira uma letra que você deseja jogar.");
            } else {
                meuCliente.chutarLetra(letra.charAt(0));
                txtPalavra.setText(meuCliente.getMascara());
                exibirPontuacao();
                exibirLetrasTentadas();
            }
            if (meuCliente.getChances() == 0) {
                JOptionPane.showMessageDialog(this, "Infelizmente não foi dessa vez, você perdeu! =(");
                txtPalavra.setText(meuCliente.getPalavra());
                txtResultado.setText("Derrota!");
                meuCliente.atualizaPlacar("DERROTA");
            }
            if (!meuCliente.getMascara().contains("_")) {
                JOptionPane.showMessageDialog(this, "Parabéns " + meuCliente.getJogador() + "! você ganhou! =)");
                txtResultado.setText("Vitória!");
                meuCliente.atualizaPlacar("VITORIA");
            }
            letraChute.setText("");
        }
    }//GEN-LAST:event_btnEnviarLetraActionPerformed

    private void letraChuteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_letraChuteKeyReleased
        try {
            if (letraChute.getText() != null || !letraChute.getText().isEmpty()) {
                letraChute.setText(String.valueOf(letraChute.getText().charAt(0)));
            }
        } catch (StringIndexOutOfBoundsException e) {

        }
    }//GEN-LAST:event_letraChuteKeyReleased

    private void txtChancesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChancesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChancesActionPerformed

    private void txtJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJogadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJogadorActionPerformed

    private void txtLetrasTentadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLetrasTentadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLetrasTentadasActionPerformed

    private void txtResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultadoActionPerformed

    private void btnMeuHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMeuHistoricoActionPerformed
        String acertos = "";
        String erros = "";
        meuCliente.solicitarHistoricoJogador();
        
        for(String palavra: meuCliente.getPalavrasAcertadas())
        {
            acertos += palavra + ", ";
        }
        
        for(String palavra: meuCliente.getPalavrasErradas())
        {
            erros += palavra + ", ";
        }
        JOptionPane.showMessageDialog(this, "Seu histórico: \n Palavras acertadas: " + acertos + "\n Palavras erradas: " + erros);
        
    }//GEN-LAST:event_btnMeuHistoricoActionPerformed

    private void btnPlacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlacarActionPerformed
        meuCliente.obterPlacar();
        JOptionPane.showMessageDialog(this, "Placar: \n" + meuCliente.getPlacar());
    }//GEN-LAST:event_btnPlacarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviarLetra;
    private javax.swing.JButton btnMeuHistorico;
    private javax.swing.JButton btnNovoTermo;
    private javax.swing.JButton btnPlacar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField letraChute;
    private javax.swing.JTextField txtChances;
    private javax.swing.JTextField txtJogador;
    private javax.swing.JTextField txtLetrasTentadas;
    private javax.swing.JTextField txtPalavra;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
